version: "2"
run:
  modules-download-mode: readonly
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: false
linters:
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nilerr
    - noctx
    - predeclared
    - revive
    - thelper
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (io.Closer).Close
    gocritic:
      disabled-checks:
        - unnamedResult
        - hugeParam
        - uncheckedInlineErr
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G404
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - all
        path: zz_generated\.deepcopy\.go
      - linters:
          - revive
        path: _test\.go
        text: should not use dot imports
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
