apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: {{CA_DATA}}
    server: {{CLUSTER_SERVER}}
  name: {{CLUSTER_NAME}}
contexts:
- context:
    cluster: {{CLUSTER_NAME}}
    namespace: {{DEFAULT_NAMESPACE}}
    user: {{USER_NAME}}
  name: {{CONTEXT_NAME}}
current-context: {{CONTEXT_NAME}}
preferences: {}
users:
- name: {{USER_NAME}}
  user:
    token: {{SERVICE_ACCOUNT_TOKEN}}
