{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rbac-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rbac-manager.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "rbac-manager.selectorLabels" . | nindent 6 }}
{{- end }}
